### Music Workflow - Test Endpoints

### Variables
@baseUrl = http://localhost:5500
@type=midi
#@type=midi

### POST /startmusic - HBD
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "Happy",
  "Bpm": 120,
  "Repeats": 1,
  "Notes": [
    { "Id": "1",  "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/16", "Interval": "0"   },
    { "Id": "2",  "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/8",  "Interval": "1/8" },
    { "Id": "3",  "NoteName": "A3", "Type": "{{type}}", "NoteLength": "1/8",  "Interval": "1/8" },
    { "Id": "4",  "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" },
    { "Id": "5",  "NoteName": "C4", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" },
    { "Id": "6",  "NoteName": "B3", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" },
    { "Id": "7",  "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/16", "Interval": "1/2" },
    { "Id": "8",  "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/8",  "Interval": "1/8" },
    { "Id": "9",  "NoteName": "A3", "Type": "{{type}}", "NoteLength": "1/8",  "Interval": "1/8" },
    { "Id": "10", "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" },
    { "Id": "11", "NoteName": "D4", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" },
    { "Id": "12", "NoteName": "C4", "Type": "{{type}}", "NoteLength": "1/4",  "Interval": "1/4" }
  ]
}

### POST /startmusic -Rick
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "Rick",
  "Bpm": 100,
  "Repeats": 1,
  "Notes": [
    { "Id": "1", "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/4." },
    { "Id": "2", "NoteName": "A3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8"  },
    { "Id": "3", "NoteName": "C4", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8"  },
    { "Id": "4", "NoteName": "A3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8"  },
    { "Id": "5", "NoteName": "E4", "Type": "{{type}}", "NoteLength": "1/4", "Interval": "1/8"  },
    { "Id": "6", "NoteName": "E4", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/4"  },
    { "Id": "7", "NoteName": "D4", "Type": "{{type}}", "NoteLength": "1/4.","Interval": "1/4"  }
  ]
}

### POST /startmusic - ST
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "Stranger",
  "Bpm": 150,
  "Repeats": 3,
  "Notes": [
    { "Id": "1", "NoteName": "C3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "2", "NoteName": "E3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "3", "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "4", "NoteName": "B3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "5", "NoteName": "C4", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "6", "NoteName": "B3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "7", "NoteName": "G3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" },
    { "Id": "8", "NoteName": "E3", "Type": "{{type}}", "NoteLength": "1/8", "Interval": "1/8" }
  ]
}



### GET
@instanceId = {{request.response.body.$.instanceId}}
GET {{baseUrl}}/musicstatus/{{instanceId}}

### PAUSE
POST {{baseUrl}}/pause/{{instanceId}}

### APPROVE
POST {{baseUrl}}/approve/{{instanceId}}/true

### SKIP
POST {{baseUrl}}/approve/{{instanceId}}/false

### TERMINATE
POST {{baseUrl}}/terminate/{{instanceId}}

### Post NoteStreamApp notes to test SSE
@noteStreamBaseUrl = http://localhost:5051
POST {{noteStreamBaseUrl}}/sendnote
Content-Type: application/json

{
  "Id": "1",
  "NoteName": "C3",
  "Type": "midi",
  "DurationMs": 500
}
