### Music Workflow - Test Endpoints

### Variables
@baseUrl = http://localhost:5000

### POST /startmusic - Send a music score
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "ST",
  "Notes": [
    {
      "Id": "1",
      "NoteName": "C3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "2",
      "NoteName": "E3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "3",
      "NoteName": "G3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "4",
      "NoteName": "B3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "5",
      "NoteName": "C4",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "6",
      "NoteName": "B3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "7",
      "NoteName": "G3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    },
    {
      "Id": "8",
      "NoteName": "E3",
      "Type": "midi",
      "DurationMs" : 100,
      "WaitMs": 200
    }
  ]
}

### GET
@instanceId = {{request.response.body.$.instanceId}}
GET {{baseUrl}}/musicstatus/{{instanceId}}

### Post NoteStreamApp notes to test SSE
@noteStreamBaseUrl = http://localhost:5051
POST {{noteStreamBaseUrl}}/sendnote
Content-Type: application/json

{
  "Id": "1",
  "NoteName": "C3",
  "Type": "midi",
  "DurationMs": 500
}
