### Music Workflow - Test Endpoints

### Variables
@baseUrl = http://localhost:5500
@notelength = 500
@waittime = 500

### POST /startmusic - HBD
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "Happy",
  "Notes": [
    { "Id": "1",  "NoteName": "G3", "Type": "audio", "DurationMs": 150, "WaitMs": 0 },
    { "Id": "2",  "NoteName": "G3", "Type": "audio", "DurationMs": 250, "WaitMs": 250 },
    { "Id": "3",  "NoteName": "A3", "Type": "audio", "DurationMs": 250, "WaitMs": 200 },
    { "Id": "4",  "NoteName": "G3", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "5",  "NoteName": "C4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "6",  "NoteName": "B3", "Type": "audio", "DurationMs": 500, "WaitMs": 500 },
    { "Id": "7",  "NoteName": "G3", "Type": "audio", "DurationMs": 150, "WaitMs": 1000 },
    { "Id": "8",  "NoteName": "G3", "Type": "audio", "DurationMs": 250, "WaitMs": 250 },
    { "Id": "9",  "NoteName": "A3", "Type": "audio", "DurationMs": 250, "WaitMs": 200 },
    { "Id": "10", "NoteName": "G3", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "11", "NoteName": "D4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "12", "NoteName": "C4", "Type": "audio", "DurationMs": 500, "WaitMs": 500 },
    { "Id": "13", "NoteName": "G3", "Type": "audio", "DurationMs": 150, "WaitMs": 1000 },
    { "Id": "14", "NoteName": "G3", "Type": "audio", "DurationMs": 250, "WaitMs": 250 },
    { "Id": "15", "NoteName": "G4", "Type": "audio", "DurationMs": 250, "WaitMs": 200 },
    { "Id": "16", "NoteName": "E4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "17", "NoteName": "C4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "18", "NoteName": "B3", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "19", "NoteName": "A3", "Type": "audio", "DurationMs": 500, "WaitMs": 500 },
    { "Id": "20", "NoteName": "F4", "Type": "audio", "DurationMs": 150, "WaitMs": 1000 },
    { "Id": "21", "NoteName": "F4", "Type": "audio", "DurationMs": 250, "WaitMs": 250 },
    { "Id": "22", "NoteName": "E4", "Type": "audio", "DurationMs": 250, "WaitMs": 200 },
    { "Id": "23", "NoteName": "C4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "24", "NoteName": "D4", "Type": "audio", "DurationMs": 350, "WaitMs": 500 },
    { "Id": "25", "NoteName": "C4", "Type": "audio", "DurationMs": 500, "WaitMs": 500 }
  ]
}

### POST /startmusic - ST
# @name request
POST {{baseUrl}}/startmusic
Content-Type: application/json

{
  "Title": "Stranger",
  "Notes": [
    { "Id": "1", "NoteName": "C3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "2", "NoteName": "E3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "3", "NoteName": "G3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "4", "NoteName": "B3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "5", "NoteName": "C4", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "6", "NoteName": "B3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "7", "NoteName": "G3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} },
    { "Id": "8", "NoteName": "E3", "Type": "midi", "DurationMs": {{notelength}}, "WaitMs": {{waittime}} }
  ]
}



### GET
@instanceId = {{request.response.body.$.instanceId}}
GET {{baseUrl}}/musicstatus/{{instanceId}}

### Post NoteStreamApp notes to test SSE
@noteStreamBaseUrl = http://localhost:5051
POST {{noteStreamBaseUrl}}/sendnote
Content-Type: application/json

{
  "Id": "1",
  "NoteName": "C3",
  "Type": "midi",
  "DurationMs": 500
}
